### ISSUE TITLE
User can generate new Eevee.

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/previous-ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the button "Call your Eevee!" to generate a new Eevee and then give it a nickname.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture (1)](https://user-images.githubusercontent.com/80491609/121612278-f133f880-ca0e-11eb-8123-b3a8a1e52145.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML skeleton and add in all necessary tags for the Home page.
- [x] Style the home page using CSS.
- [x] Hide the Eevee, nickname text, input box, submit button, and evolution stones. Don't mind the "Night Time" text and button, the heart, and the user interaction text just yet.
- [x] Query the "Call your Eevee!" button and the container containing the above hidden elements
- [x] Add a 'click' event listener to the "Call your Eevee!" button that will generate the Eevee and make everything that was hidden from a previous step appear by changing their class names. 
- [x] Add another 'click' event listener to the submit button. Once submit is pressed, the "Name your Eevee!" text, input field, and submit button should disappear and in their place a concatenated string with the nickname should appear.
- [x] Use JSON Window.localStorage to store the nickname that user entered into the nickname input text field.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
