### ISSUE TITLE
User can make Eevee evolve

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/previous-ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on one of the three evolution stones to make their Eevee evolve into the according evolution.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be shown their nickname Eevee and can click on any of the evolution stones to evolve their Eevee.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/121751402-e63aa000-cac2-11eb-8332-c2ce82ef32b4.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] For now, ignore the heart, the "night time" text & button, and the "yes" button and the "no, go to farm" button. 
- [x] Create a new row of text that will appear after the user submits a nickname that prompts the user to click on one of the elemental stones to make Eevee evolve. 
- [x] Query each elemental stone and add 'click' event listeners to each that will make Eevee evolve into the according evolution.
- [x] Create new row of text that appears congratulating the user that their eevee evolved into the correct eeveelution.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
