### ISSUE TITLE
User can toggle app to day or night

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/previous-ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can toggle on night time or day time to switch the times. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Night/Day time button is clickable and once clicked, it will turn night or day. Day being the default.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/122117480-c2859b80-cddb-11eb-88d5-1772c0576aed.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Ignore the heart for now.
- [x] Add a button that will activate night time.
- [x] Add text "Night Time" to indicate to the user what the button is for.
- [x] Query the night time button.
- [x] Add a 'click' event listener that will trigger the background to go black
- [x] Add a CSS class that will change the background to black
- [x] Add a button that will activate day time.
- [x] Add text "Day Time" to indicate to the user what the button is for.
- [x] Query the day time button.
- [x] Add a 'click' event listener that will trigger the background to go back to day time.
- [x] Add the moon. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
