### ISSUE TITLE
User can evolve Eevee based on time

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/previous-ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on the heart to evolve their Eevee into an Espeon or Umbreon.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Depending on whether it's day time (default) or night time, clicking on the heart will either evolve their Eevee into an Espeon or an Umbreon. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/122268607-21591c80-ce91-11eb-9602-bc455c708528.PNG)
![Capture1](https://user-images.githubusercontent.com/80491609/122268616-2322e000-ce91-11eb-9adc-e87211c4718b.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add the heart and use CSS to align the heart.
- [x] Query the heart.
- [x] Add a 'click' event listener to the heart so that when clicked on, Eevee will evolve into Espeon or Umbreon.
- [x] The function for evolving an Eevee into an Espeon or Umbreon needs to check if it's day time or night time. 
- [x] Add in the sun if user decides to evolve into an Espeon.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
