### ISSUE TITLE
User can generate new Eevee to start over

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/previous-ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

After evolving an Eevee, user is able to go back to the first screen and nickname another Eevee to start process all over again.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After evolving an Eevee, user will be able to see a button that allows them to go back to the Eevee nicknaming screen to evolve another Eevee. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/80491609/122452704-65feb980-cf5e-11eb-8cd7-910b0c114cda.PNG)
![Capture2](https://user-images.githubusercontent.com/80491609/122452715-672fe680-cf5e-11eb-8ba9-08613685fe87.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Ignore the red button for now. 
- [x] Create a button the shows up at the end/evolution screen and prompts user if they want to go back and evolve another Eevee.
- [x] Style the button using CSS.
- [x] Query the button.
- [x] Add click event listener that will bring user back to the nicknaming screen.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
